### PR TITLE
Handle touch events correctly inside ScrollView

### PR DESCRIPTION
**Pull request by andgeno**
Working solution for issue #1

### CODE REVIEW

**Comment by BeppiMenozzi** [comment]
Thank you very much! This fixes a problem, but evidentiated to me another problem, that comes with BalloonPopups: they don't scroll with the ScrollView, expecially when they are permanent. I'll merge this anyway, and see if I can fix the other one :)

**Comment by andgeno** [comment]
You're welcome. I have made a couple more additions in the meanwhile. Since I'm on a dead line with my project at the moment, I can't tell you when I find the time to create PRs for them.

My others additions are:
- Support fractions (2 digits at the moment)
- Support positive and negative range with zero centered at the top incl. proper half-rendering of either side for markers
- Added "smartmode" for when moving current value from negative to positive value (or vice versa), an artifical step to zero will be made for easy value resetting (optionally keeps fractions or removes them).
- Added/improved click listener to only react on clicks inside knob circle area
- Improved rendering performance (significantly)

**Comment by andgeno** [comment]
Oh and about the balloon popup issue. You're right. I didn't need it so I disabled it for now in my use-case. Sorry about that. ;-)

**Comment by BeppiMenozzi** [comment]
:-) Things are there to be enabled and disabled!
Please, if you can, let me know if you happen to use it in an app!

**Pull request merged**
